//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Client.CountriesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080", ConfigurationName="CountriesService.CountriesPort")]
    public interface CountriesPort {
        
        // CODEGEN: Generating message contract since the operation getCountry is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RSI_Client.CountriesService.getCountryResponse1 getCountry(RSI_Client.CountriesService.getCountryRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RSI_Client.CountriesService.getCountryResponse1> getCountryAsync(RSI_Client.CountriesService.getCountryRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080")]
    public partial class getCountryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8080")]
    public partial class country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int populationField;
        
        private string capitalField;
        
        private currency currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int population {
            get {
                return this.populationField;
            }
            set {
                this.populationField = value;
                this.RaisePropertyChanged("population");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string capital {
            get {
                return this.capitalField;
            }
            set {
                this.capitalField = value;
                this.RaisePropertyChanged("capital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public currency currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8080")]
    public enum currency {
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        PLN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080")]
    public partial class getCountryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private country countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public country country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCountryRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080", Order=0)]
        public RSI_Client.CountriesService.getCountryRequest getCountryRequest;
        
        public getCountryRequest1() {
        }
        
        public getCountryRequest1(RSI_Client.CountriesService.getCountryRequest getCountryRequest) {
            this.getCountryRequest = getCountryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCountryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080", Order=0)]
        public RSI_Client.CountriesService.getCountryResponse getCountryResponse;
        
        public getCountryResponse1() {
        }
        
        public getCountryResponse1(RSI_Client.CountriesService.getCountryResponse getCountryResponse) {
            this.getCountryResponse = getCountryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CountriesPortChannel : RSI_Client.CountriesService.CountriesPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountriesPortClient : System.ServiceModel.ClientBase<RSI_Client.CountriesService.CountriesPort>, RSI_Client.CountriesService.CountriesPort {
        
        public CountriesPortClient() {
        }
        
        public CountriesPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountriesPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountriesPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountriesPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Client.CountriesService.getCountryResponse1 RSI_Client.CountriesService.CountriesPort.getCountry(RSI_Client.CountriesService.getCountryRequest1 request) {
            return base.Channel.getCountry(request);
        }
        
        public RSI_Client.CountriesService.getCountryResponse getCountry(RSI_Client.CountriesService.getCountryRequest getCountryRequest) {
            RSI_Client.CountriesService.getCountryRequest1 inValue = new RSI_Client.CountriesService.getCountryRequest1();
            inValue.getCountryRequest = getCountryRequest;
            RSI_Client.CountriesService.getCountryResponse1 retVal = ((RSI_Client.CountriesService.CountriesPort)(this)).getCountry(inValue);
            return retVal.getCountryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Client.CountriesService.getCountryResponse1> RSI_Client.CountriesService.CountriesPort.getCountryAsync(RSI_Client.CountriesService.getCountryRequest1 request) {
            return base.Channel.getCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Client.CountriesService.getCountryResponse1> getCountryAsync(RSI_Client.CountriesService.getCountryRequest getCountryRequest) {
            RSI_Client.CountriesService.getCountryRequest1 inValue = new RSI_Client.CountriesService.getCountryRequest1();
            inValue.getCountryRequest = getCountryRequest;
            return ((RSI_Client.CountriesService.CountriesPort)(this)).getCountryAsync(inValue);
        }
    }
}
