//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Client.EventsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="localhost:8443", ConfigurationName="EventsService.EventsPort")]
    public interface EventsPort {
        
        // CODEGEN: Generating message contract since the operation getAllEvents is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RSI_Client.EventsService.getAllEventsResponse getAllEvents(RSI_Client.EventsService.getAllEventsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RSI_Client.EventsService.getAllEventsResponse> getAllEventsAsync(RSI_Client.EventsService.getAllEventsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.event.bialystok.com")]
    public partial class getAllEventsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.event.bialystok.com")]
    public partial class @event : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private type typeField;
        
        private System.DateTime dateField;
        
        private int weekField;
        
        private int monthField;
        
        private int yearField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public type type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int week {
            get {
                return this.weekField;
            }
            set {
                this.weekField = value;
                this.RaisePropertyChanged("week");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.event.bialystok.com")]
    public enum type {
        
        /// <remarks/>
        SPORT,
        
        /// <remarks/>
        CULTURAL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllEventsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.event.bialystok.com", Order=0)]
        public RSI_Client.EventsService.getAllEventsRequest getAllEventsRequest;
        
        public getAllEventsRequest1() {
        }
        
        public getAllEventsRequest1(RSI_Client.EventsService.getAllEventsRequest getAllEventsRequest) {
            this.getAllEventsRequest = getAllEventsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllEventsResponse", Namespace="http://ws.event.bialystok.com", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eventList", IsNullable=false)]
        public RSI_Client.EventsService.@event[] getAllEventsResponse1;
        
        public getAllEventsResponse() {
        }
        
        public getAllEventsResponse(RSI_Client.EventsService.@event[] getAllEventsResponse1) {
            this.getAllEventsResponse1 = getAllEventsResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventsPortChannel : RSI_Client.EventsService.EventsPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventsPortClient : System.ServiceModel.ClientBase<RSI_Client.EventsService.EventsPort>, RSI_Client.EventsService.EventsPort {
        
        public EventsPortClient() {
        }
        
        public EventsPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventsPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventsPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Client.EventsService.getAllEventsResponse RSI_Client.EventsService.EventsPort.getAllEvents(RSI_Client.EventsService.getAllEventsRequest1 request) {
            return base.Channel.getAllEvents(request);
        }
        
        public RSI_Client.EventsService.@event[] getAllEvents(RSI_Client.EventsService.getAllEventsRequest getAllEventsRequest) {
            RSI_Client.EventsService.getAllEventsRequest1 inValue = new RSI_Client.EventsService.getAllEventsRequest1();
            inValue.getAllEventsRequest = getAllEventsRequest;
            RSI_Client.EventsService.getAllEventsResponse retVal = ((RSI_Client.EventsService.EventsPort)(this)).getAllEvents(inValue);
            return retVal.getAllEventsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Client.EventsService.getAllEventsResponse> RSI_Client.EventsService.EventsPort.getAllEventsAsync(RSI_Client.EventsService.getAllEventsRequest1 request) {
            return base.Channel.getAllEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Client.EventsService.getAllEventsResponse> getAllEventsAsync(RSI_Client.EventsService.getAllEventsRequest getAllEventsRequest) {
            RSI_Client.EventsService.getAllEventsRequest1 inValue = new RSI_Client.EventsService.getAllEventsRequest1();
            inValue.getAllEventsRequest = getAllEventsRequest;
            return ((RSI_Client.EventsService.EventsPort)(this)).getAllEventsAsync(inValue);
        }
    }
}
